import json, sys, threading, unittest
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import HTTPError
sys.path.insert(0, str(Path(__file__).parents[1] / "src"))
from dopos_core.server import make_server

class ServerTests(unittest.TestCase):
    def setUp(self):
        try:
            self.server=make_server("127.0.0.1", 0, ":memory:")
        except PermissionError:
            self.skipTest("loopback socket binding is unavailable in this execution sandbox")
        self.url=f"http://127.0.0.1:{self.server.server_port}"; self.thread=threading.Thread(target=self.server.serve_forever); self.thread.start()
    def tearDown(self): self.server.shutdown(); self.thread.join(); self.server.server_close(); self.server.RequestHandlerClass.service.close()
    def request(self, path, payload=None):
        req=Request(self.url+path, data=json.dumps(payload).encode() if payload is not None else None, headers={"Content-Type":"application/json"}, method="POST" if payload is not None else "GET")
        return json.loads(urlopen(req).read())
    def test_local_ui_and_approval_flow(self):
        health = self.request("/health")
        self.assertEqual(health["status"], "ok")
        self.assertTrue(health["audit_chain_valid"])
        self.assertIn("records", health)
        self.assertTrue(health["workspace"]["configured"])
        self.assertEqual(health["workspace"]["document_count"], 0)
        self.assertEqual(health["workspace"]["folder_count"], 0)
        self.assertIn("catalog_revision", health["workspace"])
        self.assertFalse(health["backup_retention"]["configured"])
        self.assertFalse(health["backup_retention"]["prune_enabled"])
        self.assertEqual(health["backup_count"], 0)
        self.assertIn("configured", health["queue"])
        self.assertIn("count", health["queue"])
        self.assertIn("next_title", health["queue"])
        self.assertIn("configured", health["automation"])
        self.assertIn("latest_result", health["automation"])
        self.assertIn("latest_title", health["automation"])
        today = self.request("/today")
        self.assertEqual(today["needs_decision"], [])
        self.assertTrue(today["recovery"]["audit_chain_valid"])
        self.assertIn("queue", today)
        self.assertIn("automation", today)
        self.assertIsInstance(today["queue"]["count"], int)
        self.assertGreaterEqual(today["queue"]["count"], 0)
        self.assertIn("next_title", today["queue"])
        self.assertIn("workspace", today)
        self.assertTrue(today["workspace"]["configured"])
        self.assertEqual(today["workspace"]["document_count"], 0)
        self.assertEqual(today["workspace"]["folder_count"], 0)
        self.assertIn("catalog_revision", today["workspace"])
        self.assertIn("safety", today)
        self.assertFalse(today["safety"]["execution_paused"])
        self.assertEqual(today["safety"]["kill_switch"], "off")
        loop = self.request("/autonomous-loop")
        self.assertIn("cycles", loop)
        self.assertEqual(loop["count"], len(loop["cycles"]))
        queue = self.request("/autonomous-loop/queue")
        self.assertIn("items", queue)
        self.assertEqual(queue["count"], len(queue["items"]))
        with self.assertRaises(HTTPError) as too_long:
            self.request("/work-items", {"title":"x" * 161, "request":"safe request"})
        self.assertEqual(too_long.exception.code, 400)
        too_long.exception.close()
        page = urlopen(self.url).read().decode()
        self.assertIn("Execute approved plan", page)
        self.assertIn("Ask dopOS anything", page)
        self.assertIn('Ask dopOS about this machine. It will create a safe plan and wait for your decision.', page)
        self.assertIn("Live Work", page)
        self.assertIn("Diary", page)
        self.assertIn("/journal.md", page)
        self.assertIn("Export Markdown", page)
        self.assertIn("Export Diary as Markdown", page)
        self.assertIn('aria-label="Ask dopOS anything"', page)
        self.assertIn('aria-label="Send request"', page)
        self.assertIn('aria-label="Export Diary as Markdown"', page)
        self.assertIn("tool-ci", page)
        self.assertIn("Available locally", page)
        self.assertIn("Export still downloads the current journal projection.", page)
        self.assertGreaterEqual(page.count("Export still downloads the current journal projection."), 2)
        self.assertIn("Find a file or folder", page)
        self.assertIn("Search stays local and reads names only.", page)
        self.assertIn("searchWorkspace", page)
        self.assertIn("loadWorkspace", page)
        self.assertGreaterEqual(page.count("loadWorkspace()"), 4)
        self.assertIn("Workspace inventory is unavailable.", page)
        self.assertIn("loadDiary()", page)
        self.assertIn("loadRecent", page)
        self.assertIn("No work yet.", page)
        self.assertIn("folder</small>", page)
        self.assertIn(' bytes</small>', page)
        self.assertIn('Host records', page)
        self.assertIn('Workspace inventory', page)
        self.assertIn('Names and paths only.', page)
        self.assertIn('Workspace snapshot', page)
        self.assertIn('catalog rev ·', page)
        self.assertIn('Autonomous loop', page)
        self.assertIn('Autonomous queue', page)
        self.assertIn('Local backup created', page)
        self.assertIn('Recovery backups', page)
        self.assertIn('Backup retention', page)
        self.assertIn('configured ·', page)
        self.assertIn('prune ·', page)
        self.assertIn('The approved run and its evidence have been recorded.', page)
        self.assertIn("Workspace is ready and empty.", page)
        self.assertIn("Local workspace directory has not been created yet.", page)
        self.assertIn("api('/today')", page)
        self.assertIn("Stop control enabled", page)
        self.assertIn("Plan rejected", page)
        self.assertIn('Preparing the smallest safe plan…', page)
        self.assertIn('Ready to execute plan', page)
        self.assertIn('Saved plan', page)
        self.assertIn('Approve</button>', page)
        self.assertIn('＋', page)
        self.assertIn('Find</button>', page)
        self.assertIn('Export Markdown</a>', page)
        self.assertIn('<h3>Today</h3>', page)
        self.assertIn('class="brand">dopOS</div>', page)
        self.assertIn("Docker</span>", page)
        self.assertIn('aria-label="Local tool status"', page)
        self.assertIn('id="clock"', page)
        self.assertIn('id="thread"', page)
        self.assertIn('id="request"', page)
        self.assertIn('id="diary"', page)
        self.assertIn('id="today"', page)
        self.assertIn('id="workspace-results"', page)
        self.assertIn('id="recent"', page)
        self.assertIn('id="workspace-query"', page)
        self.assertIn('Loading local state…', page)
        self.assertIn('Today is unavailable.', page)
        self.assertIn('No matching local documents.', page)
        self.assertIn('Searching local names…', page)
        self.assertIn('<strong>Goal</strong>', page)
        self.assertIn('<strong>Plan</strong>', page)
        self.assertIn('<strong>Build</strong>', page)
        self.assertIn('<strong>Test</strong>', page)
        self.assertIn('<strong>Verify</strong>', page)
        self.assertIn('Waiting for your request', page)
        self.assertIn('Safe actions only', page)
        self.assertIn('Approval required', page)
        self.assertIn('Evidence captured', page)
        self.assertIn('Diary updated', page)
        self.assertIn('No diary evidence recorded yet.', page)
        self.assertIn("GitHub</span>", page)
        self.assertIn("Local AI</span>", page)
        self.assertIn('<h3>Workspace</h3>', page)
        self.assertIn('<h3>Recent work</h3>', page)
        self.assertIn('<h3>Diary</h3>', page)
        self.assertIn('Reject</button>', page)
        self.assertIn('Stop</button>', page)
        self.assertIn('This plan is frozen. It contains only local, read-only checks.', page)
        self.assertIn('The approved local checks finished successfully.', page)
        self.assertIn("No action was run.", page)
        self.assertIn("Execution is blocked until it is explicitly resumed.", page)
        self.assertGreaterEqual(page.count("loadToday()"), 3)
        self.assertIn("state.queue", page)
        self.assertIn("no queued work", page)
        self.assertIn("inbox not configured", page)
        self.assertIn("state.automation", page)
        self.assertIn("no cycle recorded yet", page)
        self.assertIn("loop evidence not configured", page)
        self.assertIn("state.workspace", page)
        self.assertIn("state.safety", page)
        self.assertIn("Nothing waiting", page)
        self.assertIn("retention unset", page)
        self.assertIn("audit verified", page)
        self.assertIn("needs review", page)
        self.assertIn("retention on", page)
        self.assertIn("new work can be planned", page)
        self.assertIn("execution ready", page)
        self.assertIn("execution paused", page)
        self.assertIn("kill switch", page)
        self.assertIn("Safety control", page)
        self.assertIn("· execution ready", page)
        self.assertIn("Updated ", page)
        self.assertIn("Updated ${escape(result.updated_at)}", page)
        self.assertIn("Runtime health", page)
        self.assertIn("folders ·", page)
        self.assertIn("queue ·", page)
        self.assertIn('queue · ${result.queue && result.queue.configured ? ((result.queue.count || 0)', page)
        self.assertIn("automation ·", page)
        self.assertIn("automation · ${result.automation && result.automation.configured ? (result.automation.latest_result || 'ready') : 'unset'}", page)
        self.assertIn("Docker status", page)
        self.assertIn("No Docker details returned.", page)
        self.assertIn("GitHub repository", page)
        self.assertIn("GitHub status unavailable.", page)
        self.assertIn("Private repository", page)
        self.assertIn("Public repository", page)
        self.assertIn("Local AI models", page)
        self.assertIn("No installed models were listed.", page)
        self.assertIn("Local quality checks", page)
        self.assertIn("Local quality checks are unavailable.", page)
        self.assertIn("backups ·", page)
        self.assertIn("rev ·", page)
        self.assertIn("Local tools", page)
        self.assertIn("const labels = {docker:'Docker', github:'GitHub', ci:'CI', ollama:'Local AI'}", page)
        self.assertIn("available", page)
        self.assertIn("unavailable", page)
        self.assertIn("does not change execution", page)
        tools = self.request("/tools/status")
        self.assertEqual(set(tools), {"docker", "github", "ci", "ollama"})
        workspace = self.request("/workspace")
        self.assertEqual(workspace["count"], 0)
        self.assertTrue(workspace["configured"])
        self.assertIn("documents", workspace)
        self.assertIn("folders", workspace)
        self.assertEqual(workspace["folder_count"], 0)
        searched_workspace = self.request("/workspace?query=proposal")
        self.assertEqual(searched_workspace["query"], "proposal")
        self.assertEqual(searched_workspace["count"], 0)
        with self.assertRaises(HTTPError) as workspace_query_too_long:
            self.request("/workspace?query=" + "x" * 161)
        self.assertEqual(workspace_query_too_long.exception.code, 400)
        workspace_query_too_long.exception.close()
        self.assertEqual(self.request("/controls/kill-switch")["kill_switch"], "off")
        backups = self.request("/backups")
        self.assertEqual(backups["count"], 0)
        self.assertEqual(backups["backups"], [])
        self.assertFalse(backups["retention"]["configured"])
        self.assertFalse(backups["retention"]["prune_enabled"])
        self.assertIn("retention remains unset", backups["message"])
        item=self.request("/work-items", {"title":"Test","request":"Check Docker status"}); plan=self.request("/plans/from-request", {"work_item_id":item["id"]})
        self.assertEqual(self.request("/work-items")[0]["id"], item["id"])
        self.assertEqual(self.request(f"/work-items/{item['id']}")["plan"]["id"], plan["id"])
        self.request(f"/plans/{plan['id']}/approve", {}); done=self.request(f"/plans/{plan['id']}/execute", {})
        detail = self.request(f"/work-items/{item['id']}")
        self.assertEqual(done["state"], "completed"); self.assertEqual(detail["state"], "completed")
        self.assertEqual(detail["plan"]["results"], done["results"]); self.assertGreaterEqual(len(self.request("/diary")), 4)
        journal = self.request("/journal")
        self.assertTrue(any("Started: Test" == entry["summary"] for entry in journal))
        markdown = urlopen(self.url + "/journal.md").read().decode()
        self.assertIn("# dopOS Journal", markdown)
