"""Local-first browser surface; no framework or external assets required."""
PAGE = r'''<!doctype html><meta charset="utf-8"><title>dopOS local</title>
<style>body{margin:0;background:#101227;color:#f6f7ff;font:16px system-ui;display:grid;place-items:center;min-height:100vh}.app{width:min(900px,94vw);background:#1a1e3b;border:1px solid #515a9b;border-radius:18px;padding:24px;box-shadow:0 30px 80px #0008}h1{margin:0}small{color:#abb1dd}.row{display:flex;gap:10px;margin:16px 0}input,textarea,button{font:inherit;border-radius:10px;padding:10px;border:1px solid #5963aa}input,textarea{background:#101227;color:white;flex:1}textarea{min-height:80px}button{background:#6f75ff;color:white;cursor:pointer}.card{background:#11142b;border:1px solid #353d72;border-radius:12px;padding:14px;margin:10px 0}.muted{color:#aeb5df}.ok{color:#82edab}</style>
<main class="app"><h1>dopOS <small>local operations</small></h1><p class="muted">Create a request. dopOS freezes a safe plan; you approve it before execution.</p><label>Title <input id="title" value="Check local operations status"></label><p><label>Request <textarea id="request">Show a safe read-only status summary and record it in the Diary.</textarea></label></p><div class="row"><button onclick="create()">Create safe plan</button><button onclick="loadDiary()">Refresh Diary</button></div><section id="plan"></section><h2>Diary</h2><section id="diary" class="muted">No events yet.</section></main>
<script>const api=(path,body)=>fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}).then(async r=>{let x=await r.json();if(!r.ok)throw Error(x.error);return x});let plan;
async function create(){let w=await api('/work-items',{title:title.value,request:request.value});plan=await api('/plans',{work_item_id:w.id,actions:['status.summary','diary.preview']});document.querySelector('#plan').innerHTML=`<div class=card><b>Plan #${plan.id}</b><p>${plan.actions.join(', ')}</p><button onclick="approve()">Approve and execute</button> <button onclick="reject()">Reject</button></div>`;loadDiary()}
async function approve(){let a=await api(`/plans/${plan.id}/approve`,{});let done=await api(`/plans/${plan.id}/execute`,{});document.querySelector('#plan').innerHTML=`<div class=card><b class=ok>Completed</b><pre>${JSON.stringify(done.results,null,2)}</pre></div>`;loadDiary()}
async function reject(){await api(`/plans/${plan.id}/reject`,{});document.querySelector('#plan').innerHTML='<div class=card>Plan rejected. No action ran.</div>';loadDiary()}
async function loadDiary(){let events=await api('/diary');diary.innerHTML=events.map(e=>`<div class=card><b>${e.kind}</b><br><small>${e.created_at}</small></div>`).join('')||'No events yet.'}loadDiary();</script>'''
