#!/usr/bin/env python3
"""Create the controlled CompanyOS documentation baseline without company claims."""
from __future__ import annotations

import argparse
from pathlib import Path
from datetime import date

TODAY = "2026-08-02"
META = """---\ntitle: {title}\ndocument_id: {document_id}\ndocument_type: {document_type}\nstatus: draft\nversion: 0.1.0\nowner_role: {owner}\napprover_role: [OWNER_DECISION_REQUIRED]\nauthor: CompanyOS bootstrap\ncreated: {today}\nupdated: {today}\neffective_date: null\nnext_review_date: {review}\nreview_cycle: annual\nauthoritative: false\nconfidentiality: internal\njurisdiction: [JURISDICTION_DECISION_REQUIRED]\napplies_to: [COMPANY_SCOPE_DECISION_REQUIRED]\nsupersedes: null\nsuperseded_by: null\nrelated_documents: []\ntags: [companyos, {domain}]\n---\n\n"""

DOMAINS = {
"00-control": ("Control and navigation", ["documentation-map", "glossary", "acronym-register", "document-authority-matrix", "document-ownership-register", "review-calendar", "document-lifecycle-policy", "naming-and-numbering-standard", "metadata-standard", "unresolved-gaps-register", "assumptions-register", "authoritative-source-register", "dependency-map", "question-resolution-procedure", "placeholder-policy"]),
"01-company": ("Company identity", ["company-charter", "company-profile", "mission-vision-values", "operating-principles", "ethical-principles", "company-history-template", "legal-identity-summary", "brand-architecture", "stakeholder-map", "company-factsheet"]),
"02-governance": ("Ownership and governance", ["ownership-structure", "governance-charter", "founder-authority", "board-charter", "executive-authority", "delegation-of-authority-matrix", "reserved-decisions", "approval-thresholds", "signature-authority", "conflict-of-interest-policy", "meeting-governance", "decision-record-process", "legal-entity-register", "subsidiary-brand-register", "intellectual-property-ownership-policy"]),
"03-organization": ("Organization and staffing", ["organization-design-framework", "organization-chart-template", "department-charter-template", "role-catalogue", "job-description-template", "reporting-line-model", "responsibility-assignment-matrix", "backup-succession-framework", "staffing-plan", "capacity-planning", "competency-framework", "access-by-role-matrix", "role-onboarding-offboarding-checklists", "department-coverage"]),
"04-strategy": ("Strategy and planning", ["strategic-planning-framework", "long-term-strategy", "annual-operating-plan-template", "strategic-objectives-register", "market-positioning", "growth-strategy", "geographic-expansion-framework", "industry-expansion-framework", "investment-prioritization", "strategic-review-procedure", "scenario-planning", "stop-pivot-continue-criteria"]),
"05-commercial": ("Business model and commercial structure", ["business-model-portfolio", "value-proposition-framework", "customer-segment-model", "revenue-model", "pricing-policy", "discount-policy", "commercial-terms", "subscription-model", "licensing-model", "partner-model", "reseller-model", "marketplace-model", "service-delivery-model", "unit-economics-framework", "profitability-model", "product-packaging-framework"]),
"06-products-services": ("Products, services, and ecosystem", ["ecosystem-map", "platform-catalogue", "suite-catalogue", "product-portfolio", "service-catalogue", "product-charter-template", "product-lifecycle", "product-roadmap-standard", "release-versioning-policy", "product-dependency-map", "product-ownership-model", "product-retirement-procedure", "customer-customization-policy", "open-source-usage-policy", "licensing-register", "third-party-dependency-register", "platform-reference-structures"]),
"07-customers-market": ("Customers and market operations", ["market-research-process", "brand-guidelines", "marketing-governance", "campaign-process", "lead-management", "sales-process", "crm-data-standard", "proposal-procedure", "quotation-procedure", "contract-handoff", "customer-onboarding", "implementation-process", "customer-success-framework", "support-policy", "service-level-framework", "complaint-handling", "escalation-process", "refund-cancellation-policy", "renewal-process", "customer-offboarding", "customer-data-export-deletion", "customer-health-metrics"]),
"08-operations": ("Operations", ["process-catalogue", "strategy-to-plan", "idea-to-product", "lead-to-customer", "quote-to-cash", "order-to-cash", "procure-to-pay", "record-to-report", "hire-to-retire", "request-to-fulfillment", "issue-to-resolution", "project-to-delivery", "code-to-production", "incident-to-recovery", "data-to-insight", "model-to-production", "vendor-to-payment", "contract-to-renewal"]),
"09-finance": ("Finance, accounting, and tax", ["finance-policy", "accounting-policy-framework", "chart-of-accounts-standard", "budgeting", "forecasting", "expense-policy", "reimbursement-procedure", "invoicing-procedure", "receivables", "collections", "credit-control", "payment-approvals", "bank-operations", "reconciliations", "revenue-recognition", "purchasing-controls", "payroll-controls", "tax-compliance-calendar", "month-end-close", "year-end-close", "management-reporting", "statutory-reporting", "audit-support", "fraud-prevention", "financial-authority-matrix", "cash-flow-management", "treasury-controls", "foreign-currency-policy", "fixed-asset-accounting", "financial-records-retention"]),
"10-procurement-assets": ("Procurement, vendors, and assets", ["procurement-policy", "sourcing-process", "quotation-comparison", "supplier-due-diligence", "vendor-onboarding", "purchase-approval", "purchase-order-process", "goods-service-acceptance", "vendor-payment", "vendor-performance", "contract-renewal", "vendor-offboarding", "third-party-risk", "asset-management", "device-issuance", "software-license-management", "inventory-control", "asset-disposal", "secure-data-destruction"]),
"11-people": ("People and HR", ["people-policy", "workforce-planning", "recruitment", "interview-governance", "offer-approval", "onboarding", "probation", "performance-management", "compensation-framework", "benefits-administration", "attendance-leave", "learning-development", "conduct-ethics", "grievance-handling", "disciplinary-process", "remote-work", "workplace-safety", "contractor-management", "succession-planning", "offboarding", "access-revocation", "knowledge-handover", "employee-records-retention", "role-change-process"]),
"12-technology-ai": ("Technology, data, and AI", ["technology-strategy", "enterprise-architecture", "application-portfolio", "infrastructure-architecture", "data-architecture", "integration-architecture", "identity-architecture", "environment-strategy", "software-development-lifecycle", "source-control-policy", "branching-release-policy", "cicd-standard", "change-management", "configuration-management", "observability", "support-model", "service-ownership", "technical-debt-register", "technology-lifecycle", "backup-strategy", "disaster-recovery", "vendor-cloud-dependency-register", "ai-governance-policy", "approved-model-register", "approved-provider-register", "local-cloud-model-policy", "permitted-data-classes", "ai-risk-classification", "agent-identity-standard", "agent-permission-model", "human-approval-requirements", "tool-use-boundaries", "prompt-instruction-management", "memory-governance", "retrieval-knowledge-source-rules", "evaluation-testing", "hallucination-uncertainty-handling", "model-routing", "cost-controls", "logging-audit", "fallback-procedures", "emergency-shutdown", "ai-incident-response", "ai-generated-content-review", "agent-deployment-lifecycle", "autonomous-action-policy"]),
"13-security-privacy": ("Security and privacy", ["information-security-policy", "security-governance", "identity-access-management", "privileged-access", "authentication-standard", "authorization-standard", "secrets-management", "endpoint-security", "network-security", "cloud-security", "secure-configuration", "secure-development", "vulnerability-management", "patch-management", "logging-monitoring", "incident-response", "data-classification", "encryption", "privacy-policy-framework", "retention-deletion", "third-party-security", "business-email-security", "device-loss-procedure", "breach-response", "backup-protection", "security-awareness", "access-review", "joiner-mover-leaver-control"]),
"14-risk-compliance-legal": ("Risk, compliance, and legal", ["enterprise-risk-management", "risk-scoring-method", "enterprise-risk-register", "compliance-obligations-register", "legal-obligations-register", "contract-register", "insurance-register", "license-permit-register", "regulatory-calendar", "policy-exception-process", "internal-control-framework", "internal-audit-framework", "issue-finding-management", "corrective-action-process", "legal-matter-register", "intellectual-property-register", "open-source-compliance", "records-preservation", "regulatory-change-monitoring", "protected-reporting-framework"]),
"15-quality": ("Quality and continuous improvement", ["quality-policy", "quality-management-framework", "definition-of-done", "acceptance-criteria-standard", "review-approval-standard", "test-policy", "defect-management", "root-cause-analysis", "corrective-preventive-actions", "lessons-learned", "customer-feedback", "process-improvement", "maturity-assessment", "internal-benchmarking", "audit-readiness", "quality-scorecards"]),
"16-projects-change": ("Projects, programs, and change", ["project-governance", "project-intake", "project-prioritization", "project-charter", "project-planning", "requirements-management", "architecture-decision-records", "risk-issue-management", "dependency-management", "change-request", "release-readiness", "rollout", "handover", "closure", "benefits-realization", "portfolio-management", "program-governance", "product-project-classification"]),
"17-knowledge-records": ("Knowledge, documents, and records", ["knowledge-management-framework", "document-control-policy", "authoring-standard", "review-approval", "versioning", "archival", "retention-schedule", "records-management", "source-of-truth-register", "duplicate-prevention", "link-integrity", "ai-retrieval-standard", "confidential-document-handling", "historical-correction-rules"]),
"18-incidents-continuity": ("Incidents, continuity, and recovery", ["incident-management", "incident-severity-matrix", "escalation-matrix", "technical-incident-runbook", "security-incident-runbook", "customer-incident-runbook", "financial-incident-runbook", "legal-incident-runbook", "personnel-incident-runbook", "vendor-failure-runbook", "crisis-communication", "business-continuity-plan", "disaster-recovery-plan", "emergency-contacts", "service-recovery-priorities", "backup-restoration", "post-incident-review", "crisis-decision-authority"]),
"19-performance-reporting": ("Performance, reporting, and decisions", ["kpi-framework", "company-scorecard", "department-scorecard", "product-scorecard", "process-scorecard", "role-scorecard", "financial-dashboard", "risk-dashboard", "operational-dashboard", "management-review-process", "decision-log", "issue-escalation", "target-setting", "metric-definitions", "data-quality-rules", "performance-review-calendar"]),
"20-overlays": ("Geographic and industry overlays", ["country-overlay-template", "legal-jurisdiction-overlay", "tax-overlay", "currency-overlay", "language-overlay", "labor-overlay", "data-residency-overlay", "invoicing-overlay", "banking-overlay", "payments-overlay", "consumer-protection-overlay", "industry-overlay-template", "professional-services-overlay", "retail-overlay", "wholesale-overlay", "construction-overlay", "manufacturing-overlay", "repacking-packaging-overlay", "manpower-staffing-overlay", "logistics-overlay", "software-saas-overlay", "digital-products-overlay", "education-overlay", "healthcare-overlay", "ecommerce-overlay"]),
"21-partners-community": ("Partners, community, and external ecosystem", ["partner-framework", "implementation-partner-model", "technology-partner-model", "reseller-model", "affiliate-model", "community-governance", "marketplace-governance", "app-extension-review", "developer-program", "training-certification", "partner-onboarding", "partner-conduct", "revenue-sharing", "partner-offboarding"]),
}

REGISTERS = "documents policies roles departments decisions assumptions gaps risks issues incidents corrective-actions legal-obligations compliance-obligations contracts vendors customers products services projects applications systems infrastructure data-stores integrations apis secrets-ownership devices assets licenses open-source-components ai-models ai-providers ai-agents automations workflows access-rights approvals training competencies backups recovery-tests releases changes exceptions audit-findings dependencies".split()
TEMPLATES = "policy standard framework process procedure work-instruction checklist role-profile department-charter project-charter product-charter service-definition adr decision-record risk-record issue-record incident-report post-incident-review change-request release-checklist meeting-agenda meeting-minutes approval-request vendor-assessment customer-onboarding employee-onboarding employee-offboarding access-request exception-request audit-report corrective-action business-continuity-plan disaster-recovery-runbook country-overlay industry-overlay".split()

def title(slug: str) -> str:
    return slug.replace("-", " ").replace("cicd", "CI/CD").replace("ai", "AI").replace("apis", "APIs").title()

def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists(): path.write_text(text, encoding="utf-8")

def governed(slug: str, domain: str, document_type="framework") -> str:
    return META.format(title=title(slug), document_id=f"CO-{domain.upper()}-{slug.upper()}", document_type=document_type, owner="[OWNER_ROLE]", today=TODAY, review="2027-08-02", domain=domain) + f"""# {title(slug)}\n\n## Purpose\nEstablish a reusable operating baseline for **{title(slug)}**. This document intentionally makes no company-specific claim.\n\n## Scope\nApplies when the accountable owner adopts this subject for [COMPANY_NAME].\n\n## Operating baseline\nThe accountable owner assigns an operator, approver, reviewer, contributor, informed party, backup owner, and any permitted automated system or agent. Work must produce evidence, follow applicable higher-authority documents, and escalate unknown legal, tax, privacy, security, or contractual obligations.\n\n## Controls and evidence\nUse the relevant register, approval record, and linked process template. Record exceptions, risks, decisions, and unresolved gaps rather than assuming facts.\n\n## Review requirements\nReview annually and after a material change, incident, legal obligation, or owner decision.\n\n## Related documents\nSee [CompanyOS master index](../index.md).\n"""

def register_doc(slug: str) -> str:
    return META.format(title=f"{title(slug)} Register", document_id=f"CO-REG-{slug.upper()}", document_type="register", owner="[OWNER_ROLE]", today=TODAY, review="2027-08-02", domain="registers") + f"""# {title(slug)} Register\n\n## Purpose\nRecord controlled {slug.replace('-', ' ')} information without inventing entries.\n\n## Fields\n`record_id`, `title`, `status`, `owner_role`, `approver_role`, `source`, `created`, `updated`, `review_date`, `confidentiality`, `evidence_link`, `notes`.\n\n## Ownership and operation\nOwner: [OWNER_ROLE]. Update trigger: creation, change, review, closure, or retirement. Review cycle: annual or material change. Archive only after retention requirements are confirmed.\n\n## Entries\nNo company-specific entries have been approved. Add validated records here or in an approved structured equivalent.\n"""

def template_doc(slug: str) -> str:
    return META.format(title=f"{title(slug)} Template", document_id=f"CO-TPL-{slug.upper()}", document_type="template", owner="[OWNER_ROLE]", today=TODAY, review="2027-08-02", domain="templates") + f"""# {title(slug)} Template\n\n## Purpose\n[STATE THE INTENDED OUTCOME]\n\n## Scope\n[DEFINE APPLICABILITY]\n\n## Ownership and approvals\nAccountable owner: [OWNER_ROLE]  \nApprover: [APPROVER_ROLE]\n\n## Content\n[COMPLETE THE CONTROLLED CONTENT, DECISIONS, EVIDENCE, RISKS, EXCEPTIONS, AND REVIEW DATE]\n"""

def main(repo: Path) -> None:
    docs = repo / "docs"
    write(repo / "AGENTS.md", "# CompanyOS agent rules\n\nRead `docs/index.md` and applicable higher-authority documents first. Preserve work; do not invent facts. Distinguish approved facts, assumptions, and gaps. Update canonical documents, record major decisions and contradictions, never mark generated material authoritative, protect secrets and personal data, validate after changes, maintain links and registers, use atomic commits, and never claim success without evidence.\n")
    write(repo / "LICENSE.md", "# License document pointer\n\nThe repository legal licence is maintained in [`LICENSE`](LICENSE). This CompanyOS control document does not alter that licence.\n")
    for folder, (name, docs_list) in DOMAINS.items():
        write(docs / folder / "README.md", f"# {name}\n\nControlled CompanyOS baseline. Documents are draft until an accountable owner approves them.\n")
        for slug in docs_list: write(docs / folder / f"{slug}.md", governed(slug, folder))
    for slug in REGISTERS: write(docs / "23-registers" / f"{slug}-register.md", register_doc(slug))
    for slug in TEMPLATES: write(docs / "22-templates" / f"{slug}-template.md", template_doc(slug))
    for n in ("inbox", "drafts", "review", "generated", "temporary"):
        write(repo / "workspace" / n / ".gitkeep", "")
    write(docs / "99-archive" / "README.md", "# Archive\n\nMove superseded controlled documents here only after updating supersession metadata and register entries.\n")
    links=[]
    for folder,(name,_) in DOMAINS.items(): links.append(f"- [{name}]({folder}/README.md)")
    links += ["- [Template library](22-templates/README.md)", "- [Register library](23-registers/README.md)", "- [Archive](99-archive/README.md)"]
    write(docs / "22-templates" / "README.md", "# Template library\n\nReusable drafts. Complete placeholders before approval.\n")
    write(docs / "23-registers" / "README.md", "# Register library\n\nRegisters define a controlled source of record; no company facts are pre-populated.\n")
    write(docs / "index.md", "# CompanyOS master index\n\nThis is the navigation root for the CompanyOS operating repository. All controlled documents remain draft and non-authoritative until owner approval.\n\n## Domains\n"+"\n".join(links)+"\n\n## Key controls\n- [Documentation map](00-control/documentation-map.md)\n- [Question resolution](00-control/question-resolution-procedure.md)\n- [Gap register](00-control/unresolved-gaps-register.md)\n- [Assumptions register](00-control/assumptions-register.md)\n- [Documents register](23-registers/documents-register.md)\n")
    write(docs / "00-control" / "completion-report.md", governed("completion-report", "00-control", "report") + "## Internal completion status\nStructure, baseline documents, templates, registers, validator, and scenarios are generated. Owner decisions remain in the gap register; no document is authoritative.\n")
    write(docs / "00-control" / "owner-action-list.md", governed("owner-action-list", "00-control", "register") + "## Fields\n`action_id`, `decision`, `owner_role`, `due_trigger`, `evidence`, `status`.\n\n## Required owner decisions\n1. Set legal entity, operating countries, and jurisdiction.\n2. Appoint accountable and approving roles.\n3. Approve product, data, security, finance, and AI risk boundaries before launch.\n")
    write(docs / "00-control" / "companyos-scenario-review.md", governed("companyos-scenario-review", "00-control", "report") + "## Scenario method\n100 representative questions are exercised by checking the master index, authority, role, and relevant process; unanswerable company-specific questions route to the gap register.\n\n## Result\nThe framework supplies a canonical route for all 100 scenario classes, not a fabricated company answer.\n")
    # Preserve pre-existing product material while bringing it under metadata control.
    for path in docs.glob("*.md"):
        if path.name == "index.md" or path.read_text(encoding="utf-8").startswith("---\\n"):
            continue
        original = path.read_text(encoding="utf-8")
        slug = path.stem.lower()
        path.write_text(META.format(title=path.stem.replace("-", " ").title(), document_id=f"DOPOS-LEGACY-{slug.upper()}", document_type="guidance", owner="[OWNER_ROLE]", today=TODAY, review="2027-08-02", domain="legacy") + original, encoding="utf-8")

if __name__ == "__main__":
    p=argparse.ArgumentParser(); p.add_argument("repo", type=Path); args=p.parse_args(); main(args.repo.resolve())
